[EventLogRecord(storage_id=28, 
                event_log_entry=EventLogEntry(error_info=None, 
                                              level=10, 
                                              user_message='Inserting a random batch of records', 
                                              run_id='77679426-200d-4a5f-9f50-892c527b3ec2', 
                                              timestamp=1685278904.048358, 
                                              step_key='latest_version', 
                                              job_name='version_job_local', 
                                              dagster_event=DagsterEvent(event_type_value='ASSET_MATERIALIZATION', 
                                                                         job_name='version_job_local', 
                                                                         step_handle=StepHandle(node_handle=NodeHandle(name='latest_version', parent=None), key='latest_version'), 
                                                                        node_handle=NodeHandle(name='latest_version', parent=None), 
                                                                        step_kind_value='COMPUTE', 
                                                                        logging_tags={'job_name': 'version_job_local', 'op_name': 'latest_version', 'resource_fn_name': 'None', 'resource_name': 'None', 'run_id': '77679426-200d-4a5f-9f50-892c527b3ec2', 'step_key': 'latest_version'}, 
                                                                        event_specific_data=StepMaterializationData(materialization=AssetMaterialization(asset_key=AssetKey(['latest_version']), 
                                                                                                                                                         description='Inserting a random batch of records', 
                                                                                                                                                         metadata={'version': IntMetadataValue(value=242)}, partition=None, tags=None), asset_lineage=[]), message='Inserting a random batch of records', pid=17239, step_key='latest_version')))]